# Generated by Django 4.1.1 on 2022-09-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Name'),
        ),
    ]
